import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { User } from '../models/User';
import { Destination } from '../models/Destination';
import { PickupLocation } from '../models/PickupLocation';
import { Vendor } from '../models/Vendor';
import { Vehicle } from '../models/Vehicle';
import { VehicleAvailability } from '../models/VehicleAvailability';
import { Booking } from '../models/Booking';
import { DigitalHandoverReport } from '../models/DigitalHandoverReport';
import { Review } from '../models/Review';
import { Coupon } from '../models/Coupon';
import { SupportTicket } from '../models/SupportTicket';
import { Notification } from '../models/Notification';

import connectToDatabase from '../lib/mongodb';

export async function seedDatabase() {
  console.log('[Seed] Connecting to MongoDB database via RideSetu connector...');
  await connectToDatabase();

  console.log('[Seed] Clearing existing collections...');
  const models = [
    User,
    Destination,
    PickupLocation,
    Vendor,
    Vehicle,
    VehicleAvailability,
    Booking,
    DigitalHandoverReport,
    Review,
    Coupon,
    SupportTicket,
    Notification,
  ];
  for (const model of models) {
    await (model as any).deleteMany({});
  }

  console.log('[Seed] Creating demo users...');
  const customerPasswordHash = await bcrypt.hash('customer123', 10);
  const vendorPasswordHash = await bcrypt.hash('vendor123', 10);
  const adminPasswordHash = await bcrypt.hash('admin123', 10);

  const [customerUser, vendorUser1, vendorUser2, vendorUser3, vendorUser4, adminUser] = await User.create([
    {
      name: 'Aarav Sharma',
      email: 'customer@ridesetu.demo',
      phone: '+91 98765 43210',
      passwordHash: customerPasswordHash,
      role: 'CUSTOMER',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
      kycStatus: 'VERIFIED',
      drivingLicenseStatus: 'VERIFIED',
      drivingLicenseNumber: 'UK0720210084920',
      emergencyContact: {
        name: 'Rohan Sharma',
        phone: '+91 98765 43219',
        relation: 'Brother',
      },
      address: {
        street: 'Sector 4, Rajpur Road',
        city: 'Dehradun',
        state: 'Uttarakhand',
        pincode: '248001',
      },
    },
    {
      name: 'Vikram Negi (Himalayan Wheels)',
      email: 'vendor@ridesetu.demo',
      phone: '+91 98111 22233',
      passwordHash: vendorPasswordHash,
      role: 'VENDOR',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80',
      kycStatus: 'VERIFIED',
      drivingLicenseStatus: 'VERIFIED',
    },
    {
      name: 'Rajesh Rawat (Tapovan Moto)',
      email: 'tapovan.moto@ridesetu.demo',
      phone: '+91 98222 33344',
      passwordHash: vendorPasswordHash,
      role: 'VENDOR',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      kycStatus: 'VERIFIED',
      drivingLicenseStatus: 'VERIFIED',
    },
    {
      name: 'Pooja Bisht (Doon Mobility)',
      email: 'doon.mobility@ridesetu.demo',
      phone: '+91 98333 44455',
      passwordHash: vendorPasswordHash,
      role: 'VENDOR',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      kycStatus: 'VERIFIED',
      drivingLicenseStatus: 'VERIFIED',
    },
    {
      name: 'Sunil Joshi (Naini Riders)',
      email: 'naini.riders@ridesetu.demo',
      phone: '+91 98444 55566',
      passwordHash: vendorPasswordHash,
      role: 'VENDOR',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      kycStatus: 'VERIFIED',
      drivingLicenseStatus: 'VERIFIED',
    },
    {
      name: 'RideSetu Super Admin',
      email: 'admin@ridesetu.demo',
      phone: '+91 99999 88888',
      passwordHash: adminPasswordHash,
      role: 'ADMIN',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
      kycStatus: 'VERIFIED',
      drivingLicenseStatus: 'VERIFIED',
    },
  ]);

  console.log('[Seed] Creating Uttarakhand destinations...');
  const destinations = await Destination.create([
    {
      name: 'Rishikesh',
      slug: 'rishikesh',
      state: 'Uttarakhand',
      heroImage: 'https://images.unsplash.com/photo-1600100397608-f010f421a99f?auto=format&fit=crop&w=1200&q=80',
      tagline: 'Yoga Capital & Adventure Gateway along the Holy Ganges',
      description: 'Explore the foothills of the Himalayas, riverside cafes in Tapovan, scenic suspension bridges, and winding mountain trails to Neelkanth and Devprayag on verified two-wheelers.',
      popularCategories: ['SCOOTER', 'MOTORCYCLE', 'EV'],
      averagePrices: { scooter: 400, motorcycle: 650, car: 1800, ev: 450 },
      travelTips: [
        'Always wear your helmet while riding through Tapovan and Laxman Jhula bypass.',
        'Carry a physical driving license along with digital RideSetu verification.',
        'Early morning rides along the Badrinath highway offer breathtaking Ganga mist views.',
        'Check fuel before ascending towards Neelkanth Temple or Shivpuri.',
      ],
      attractions: [
        { name: 'Triveni Ghat & Maha Aarti', distance: '3.5 km from Tapovan', description: 'Famous evening riverside spiritual ceremony with spectacular oil lamp offerings.', image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80' },
        { name: 'Neelkanth Mahadev Temple', distance: '28 km mountain ride', description: 'Thrilling hill road through lush Sal forests with panoramic Himalayan valleys.', image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80' },
        { name: 'Shivpuri River Camping Hub', distance: '16 km along NH 58', description: 'Riverside white water rafting base with beachside viewpoints.', image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80' },
      ],
      faqs: [
        { question: 'What documents are required to rent a scooty in Rishikesh?', answer: 'Original Valid Driving Licence and one Government ID (Aadhaar or Passport). Upload them during RideSetu booking for instant 5-minute digital pickup.' },
        { question: 'Is doorstep delivery available to Zostel or Tapovan hotels?', answer: 'Yes! All verified RideSetu partners offer doorstep delivery to hotels, hostels, and cafes across Rishikesh for a nominal fee.' },
        { question: 'Are helmets provided with the rental?', answer: 'Yes, 1 complimentary ISI-certified helmet is included with every two-wheeler. Pillion helmets can be added during checkout.' },
      ],
      safetyGuidelines: [
        'Ride cautiously around hairpin turns on the upper bypass road.',
        'Strictly avoid riding under the influence; local police checkposts are active 24/7.',
        'Adhere to the 40 km/h speed limit within city and market zones.',
      ],
      popularPickupLocations: ['Tapovan Main Market', 'Laxman Jhula Chowk', 'Rishikesh Railway Station', 'Ram Jhula Parking Hub'],
      isActive: true,
    },
    {
      name: 'Mussoorie',
      slug: 'mussoorie',
      state: 'Uttarakhand',
      heroImage: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80',
      tagline: 'The Queen of Hills overlooking the Doon Valley',
      description: 'Glide along Camel Back Road, climb up to Landour bakery, and witness golden hour sunsets from Cloud End with reliable rental scooters and Royal Enfields.',
      popularCategories: ['SCOOTER', 'MOTORCYCLE', 'CAR'],
      averagePrices: { scooter: 500, motorcycle: 750, car: 2200, ev: 550 },
      travelTips: [
        'Keep warm riding gear as temperatures dip quickly after sunset.',
        'Mall Road has vehicle time restrictions; park at designated Picture Palace or Library points.',
        'Use low gears while descending from Landour or Kempty Falls.',
      ],
      attractions: [
        { name: 'Landour & Chaar Dukan', distance: '5 km uphill', description: 'Charming colonial heritage enclave with pine-scented mountain air and pancake cafes.', image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=600&q=80' },
        { name: 'Cloud’s End Viewpoint', distance: '7 km scenic trail', description: 'Serene western edge of Mussoorie bordered by thick Deodar forests.', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80' },
        { name: 'George Everest Peak', distance: '6 km ride', description: '360-degree views of snow-capped Himalayan ranges and the glittering Doon valley.', image: 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=600&q=80' },
      ],
      faqs: [
        { question: 'Can I rent in Dehradun and drop off in Mussoorie?', answer: 'Yes! Select "One-Way Drop" during booking with verified partners supporting Dehradun-Mussoorie intercity routes.' },
        { question: 'Is a powerful bike recommended for Mussoorie?', answer: 'Both 125cc scooters (Activa/Access) and 350cc motorcycles (Royal Enfield Classic/Hunter) handle Mussoorie steep slopes comfortably.' },
      ],
      safetyGuidelines: ['Beware of mist and fog near Dhanaulti road in the evenings.', 'Maintain safe braking distance on wet hill roads.'],
      popularPickupLocations: ['Library Chowk Taxi Stand', 'Picture Palace Bus Stand', 'Kempty Fall Bypass'],
      isActive: true,
    },
    {
      name: 'Dehradun',
      slug: 'dehradun',
      state: 'Uttarakhand',
      heroImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
      tagline: 'Vibrant Valley Hub & Gateway to Uttarakhand Hills',
      description: 'Convenient rental hub for airport pickups, long mountain expeditions, Robber Cave excursions, and Sahastradhara springs.',
      popularCategories: ['SCOOTER', 'MOTORCYCLE', 'CAR', 'EV'],
      averagePrices: { scooter: 380, motorcycle: 600, car: 1600, ev: 420 },
      travelTips: [
        'Pick up directly from Jolly Grant Airport or ISBT for zero hassle.',
        'Fuel stations are abundant along Rajpur Road and Saharanpur Chowk.',
      ],
      attractions: [
        { name: 'Robber’s Cave (Guchhupani)', distance: '8 km from Clock Tower', description: 'Natural river cave with freezing cold springs inside limestone cliffs.', image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80' },
        { name: 'Mindrolling Monastery', distance: '10 km from center', description: 'One of India largest Tibetan Buddhist centers featuring a 185-ft stupa.', image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80' },
      ],
      faqs: [
        { question: 'Is delivery available at Jolly Grant Airport?', answer: 'Yes! Airport delivery points are manned by partner representatives with ready-to-ride vehicles.' },
      ],
      safetyGuidelines: ['Heavy traffic during peak hours on Rajpur Road; follow lane discipline.'],
      popularPickupLocations: ['Jolly Grant Airport (DED)', 'Dehradun ISBT Bus Terminal', 'Dehradun Railway Station', 'Clock Tower Rajpur Road'],
      isActive: true,
    },
    {
      name: 'Nainital',
      slug: 'nainital',
      state: 'Uttarakhand',
      heroImage: 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=1200&q=80',
      tagline: 'The Enchanting Lake City of Kumaon',
      description: 'Ride around the scenic rim of Naini Lake, explore hidden pine trails in Pangot, and visit Himalayan viewpoints at Snow View and Kilbury.',
      popularCategories: ['SCOOTER', 'MOTORCYCLE', 'CAR'],
      averagePrices: { scooter: 450, motorcycle: 700, car: 2000, ev: 480 },
      travelTips: ['Park in designated Tallital or Mallital areas.', 'Check weather before visiting Kilbury bird sanctuary trails.'],
      attractions: [
        { name: 'Naini Lake Circuit & Viewpoints', distance: 'Around lake basin', description: 'Crescent-shaped emerald lake surrounded by seven verdant mountain peaks.', image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80' },
        { name: 'Pangot Pine Birding Trails', distance: '15 km hill ride', description: 'Quiet oak and pine forests famous for mountain birds and tranquil valley views.', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80' },
      ],
      faqs: [{ question: 'Are two-wheelers allowed on the Mall Road?', answer: 'Two-wheelers are allowed during non-pedestrian hours; scenic bypass roads are accessible 24/7.' }],
      safetyGuidelines: ['Take extreme care on steep downhill turns during rain.'],
      popularPickupLocations: ['Tallital Bus Stand', 'Mallital Rickshaw Stand', 'Kathgodam Link Hub'],
      isActive: true,
    },
    {
      name: 'Haridwar',
      slug: 'haridwar',
      state: 'Uttarakhand',
      heroImage: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80',
      tagline: 'Ancient Holy Ghats & Shivalik Foothills',
      description: 'Convenient rental hub for spiritual pilgrims, Shivalik foothill excursions, and Rajaji National Park forest drives.',
      popularCategories: ['SCOOTER', 'MOTORCYCLE', 'CAR'],
      averagePrices: { scooter: 350, motorcycle: 550, car: 1500, ev: 400 },
      travelTips: ['Rent an electric scooter or Activa to easily navigate busy bazaar alleys.'],
      attractions: [
        { name: 'Har Ki Pauri Ghats', distance: '2 km from station', description: 'Fabled holy ghat where thousands gather for the sacred Ganga Aarti.', image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80' },
        { name: 'Chandi Devi & Mansa Devi Ridge', distance: '4 km from center', description: 'Panoramic temple hilltops overlooking the vast Gangetic plains.', image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80' },
      ],
      faqs: [{ question: 'Can I ride from Haridwar to Rishikesh?', answer: 'Yes! The Haridwar-Rishikesh highway is a smooth 25 km ride taking approximately 35 minutes.' }],
      safetyGuidelines: ['Drive carefully around crowded temple approaches and pilgrim pedestrian areas.'],
      popularPickupLocations: ['Haridwar Railway Station Hub', 'Har Ki Pauri Chowk', 'Shantikunj Gate'],
      isActive: true,
    },
    {
      name: 'Haldwani',
      slug: 'haldwani',
      state: 'Uttarakhand',
      heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
      tagline: 'Commercial Hub & Gateway to Kumaon Hills',
      description: 'The ultimate starting point for road trips into Almora, Ranikhet, Kausani, and Nainital from Kathgodam railway junction.',
      popularCategories: ['SCOOTER', 'MOTORCYCLE', 'CAR'],
      averagePrices: { scooter: 380, motorcycle: 600, car: 1600, ev: 420 },
      travelTips: ['Pick up directly at Kathgodam railway station when arriving via Shatabdi or Ranikhet Express.'],
      attractions: [
        { name: 'Kathgodam Hill Gateway', distance: '4 km from center', description: 'Scenic transition from plains to towering Himalayan foothills.', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80' },
        { name: 'Gaula Barrage & Forest Corridor', distance: '6 km scenic spot', description: 'Picturesque picnic spot on the Gaula river with migratory bird views.', image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=600&q=80' },
      ],
      faqs: [{ question: 'Is Kathgodam railway pickup available?', answer: 'Yes, partners park right opposite Kathgodam platform 1 for immediate handover.' }],
      safetyGuidelines: ['Ensure headlights and horns are tested before heading up the Ghat road.'],
      popularPickupLocations: ['Kathgodam Railway Station Hub', 'Haldwani Bus Station', 'Kaladhungi Road Hub'],
      isActive: true,
    },
  ]);

  const [rishikeshDest, mussoorieDest, dehradunDest, nainitalDest, haridwarDest, haldwaniDest] = destinations;

  console.log('[Seed] Creating pickup locations...');
  await PickupLocation.create([
    { destinationId: rishikeshDest._id, name: 'Tapovan Main Market Hub', landmark: 'Near Laxman Jhula Police Chowki', address: 'Badrinath Road, Tapovan, Rishikesh', isVendorHub: true, isDeliveryPoint: true },
    { destinationId: rishikeshDest._id, name: 'Ram Jhula Parking Area', landmark: 'Near Geeta Bhawan', address: 'Swargashram Side, Rishikesh', isVendorHub: true, isDeliveryPoint: true },
    { destinationId: rishikeshDest._id, name: 'Rishikesh Railway Station (Yog Nagari)', landmark: 'Platform 1 Exit Gate', address: 'Railway Station Road, Rishikesh', isVendorHub: false, isDeliveryPoint: true, deliveryType: 'STATION' },
    { destinationId: mussoorieDest._id, name: 'Library Chowk Hub', landmark: 'Near Gandhi Statue', address: 'The Mall Road West, Mussoorie', isVendorHub: true, isDeliveryPoint: true },
    { destinationId: mussoorieDest._id, name: 'Picture Palace Bus Stand', landmark: 'Mall Road East Entrance', address: 'Kulri Bazaar, Mussoorie', isVendorHub: true, isDeliveryPoint: true },
    { destinationId: dehradunDest._id, name: 'Jolly Grant Airport (DED) Hub', landmark: 'Arrivals Terminal Exit', address: 'Airport Road, Dehradun', isVendorHub: false, isDeliveryPoint: true, deliveryType: 'AIRPORT' },
    { destinationId: dehradunDest._id, name: 'Dehradun ISBT Terminal', landmark: 'Haridwar Bypass Exit', address: 'ISBT Complex, Dehradun', isVendorHub: true, isDeliveryPoint: true, deliveryType: 'STATION' },
    { destinationId: nainitalDest._id, name: 'Tallital Main Bus Station', landmark: 'Near Naini Lake Toll Gate', address: 'Tallital, Nainital', isVendorHub: true, isDeliveryPoint: true },
    { destinationId: haridwarDest._id, name: 'Haridwar Junction Station Hub', landmark: 'Opposite Platform 1 Parking', address: 'Station Road, Haridwar', isVendorHub: true, isDeliveryPoint: true, deliveryType: 'STATION' },
    { destinationId: haldwaniDest._id, name: 'Kathgodam Railway Station Hub', landmark: 'Outside Kathgodam Main Gate', address: 'Kathgodam, Haldwani', isVendorHub: true, isDeliveryPoint: true, deliveryType: 'STATION' },
  ]);

  console.log('[Seed] Creating 10 verified local rental vendors...');
  const vendors = await Vendor.create([
    {
      userId: vendorUser1._id,
      businessName: 'Himalayan Wheels & Expeditions',
      ownerName: 'Vikram Negi',
      email: 'vendor@ridesetu.demo',
      phone: '+91 98111 22233',
      address: 'Main Tapovan Bypass Road, near Swiss Cottage',
      city: 'Rishikesh',
      destinationId: rishikeshDest._id,
      businessType: 'PROPRIETORSHIP',
      gstNumber: '05AABCH1234F1Z8',
      rentalLicenseNumber: 'UK-RSH-RENT-2023-089',
      verificationStatus: 'VERIFIED',
      rating: 4.9,
      totalReviews: 142,
      commissionRate: 15,
      deliveryRadiusKm: 20,
      baseDeliveryFee: 120,
      bankAccountReference: 'HDFC_AC_9482716492',
      isTopRated: true,
      documents: {
        tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/himalayan_trade_lic.pdf',
        gstCertificateUrl: 'https://cdn.ridesetu.demo/docs/himalayan_gst.pdf',
        rentalPermitUrl: 'https://cdn.ridesetu.demo/docs/himalayan_permit.pdf',
      },
    },
    {
      userId: vendorUser2._id,
      businessName: 'Tapovan Moto Hub',
      ownerName: 'Rajesh Rawat',
      email: 'tapovan.moto@ridesetu.demo',
      phone: '+91 98222 33344',
      address: 'Near Laxman Jhula Chowk, Tapovan',
      city: 'Rishikesh',
      destinationId: rishikeshDest._id,
      businessType: 'INDIVIDUAL',
      rentalLicenseNumber: 'UK-RSH-RENT-2022-045',
      verificationStatus: 'VERIFIED',
      rating: 4.8,
      totalReviews: 98,
      commissionRate: 14,
      deliveryRadiusKm: 15,
      baseDeliveryFee: 100,
      isTopRated: true,
      documents: {
        tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/tapovan_trade_lic.pdf',
      },
    },
    {
      userId: vendorUser3._id,
      businessName: 'Doon Valley Mobility Partners',
      ownerName: 'Pooja Bisht',
      email: 'doon.mobility@ridesetu.demo',
      phone: '+91 98333 44455',
      address: 'Rajpur Road, Near Clock Tower',
      city: 'Dehradun',
      destinationId: dehradunDest._id,
      businessType: 'PVT_LTD',
      gstNumber: '05AACCD5566G1Z2',
      rentalLicenseNumber: 'UK-DDN-RENT-2021-112',
      verificationStatus: 'VERIFIED',
      rating: 4.9,
      totalReviews: 215,
      commissionRate: 15,
      deliveryRadiusKm: 25,
      baseDeliveryFee: 150,
      isTopRated: true,
      documents: {
        tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/doon_trade_lic.pdf',
      },
    },
    {
      userId: vendorUser4._id,
      businessName: 'Naini Lake Mountain Riders',
      ownerName: 'Sunil Joshi',
      email: 'naini.riders@ridesetu.demo',
      phone: '+91 98444 55566',
      address: 'Tallital Bus Stand Arcade',
      city: 'Nainital',
      destinationId: nainitalDest._id,
      businessType: 'PARTNERSHIP',
      rentalLicenseNumber: 'UK-NTL-RENT-2023-018',
      verificationStatus: 'VERIFIED',
      rating: 4.7,
      totalReviews: 84,
      commissionRate: 15,
      deliveryRadiusKm: 15,
      baseDeliveryFee: 120,
      isTopRated: false,
      documents: {
        tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/naini_trade_lic.pdf',
      },
    },
    {
      userId: vendorUser1._id,
      businessName: 'Mussoorie Heights Wheels',
      ownerName: 'Amit Negi',
      email: 'mussoorie.heights@ridesetu.demo',
      phone: '+91 98555 66677',
      address: 'Library Chowk, Mall Road Entry',
      city: 'Mussoorie',
      destinationId: mussoorieDest._id,
      businessType: 'PROPRIETORSHIP',
      rentalLicenseNumber: 'UK-MUS-RENT-2022-076',
      verificationStatus: 'VERIFIED',
      rating: 4.8,
      totalReviews: 126,
      commissionRate: 15,
      deliveryRadiusKm: 15,
      baseDeliveryFee: 150,
      isTopRated: true,
      documents: { tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/mussoorie_lic.pdf' },
    },
    {
      userId: vendorUser2._id,
      businessName: 'Holy Ganga Moto Tours',
      ownerName: 'Sanjay Sharma',
      email: 'ganga.tours@ridesetu.demo',
      phone: '+91 98666 77788',
      address: 'Near Har Ki Pauri Bridge, Station Road',
      city: 'Haridwar',
      destinationId: haridwarDest._id,
      businessType: 'PROPRIETORSHIP',
      rentalLicenseNumber: 'UK-HDW-RENT-2023-034',
      verificationStatus: 'VERIFIED',
      rating: 4.6,
      totalReviews: 67,
      commissionRate: 12,
      deliveryRadiusKm: 15,
      baseDeliveryFee: 100,
      isTopRated: false,
      documents: { tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/ganga_lic.pdf' },
    },
    {
      userId: vendorUser3._id,
      businessName: 'Kathgodam Hill Cruisers',
      ownerName: 'Manoj Pandey',
      email: 'kathgodam.cruisers@ridesetu.demo',
      phone: '+91 98777 88899',
      address: 'Opposite Kathgodam Railway Platform 1',
      city: 'Haldwani',
      destinationId: haldwaniDest._id,
      businessType: 'PROPRIETORSHIP',
      rentalLicenseNumber: 'UK-HLD-RENT-2023-059',
      verificationStatus: 'VERIFIED',
      rating: 4.9,
      totalReviews: 110,
      commissionRate: 15,
      deliveryRadiusKm: 20,
      baseDeliveryFee: 120,
      isTopRated: true,
      documents: { tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/kathgodam_lic.pdf' },
    },
    {
      userId: vendorUser4._id,
      businessName: 'Ganga Cruise Auto Rentals',
      ownerName: 'Deepak Bhatt',
      email: 'ganga.cruise@ridesetu.demo',
      phone: '+91 98888 99900',
      address: 'Ram Jhula Market Road',
      city: 'Rishikesh',
      destinationId: rishikeshDest._id,
      businessType: 'INDIVIDUAL',
      rentalLicenseNumber: 'UK-RSH-RENT-2024-002',
      verificationStatus: 'VERIFIED',
      rating: 4.7,
      totalReviews: 45,
      commissionRate: 14,
      deliveryRadiusKm: 12,
      baseDeliveryFee: 100,
      isTopRated: false,
      documents: { tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/ganga_cruise_lic.pdf' },
    },
    {
      userId: vendorUser1._id,
      businessName: 'Cloud Nine Mussoorie Rides',
      ownerName: 'Kunal Chauhan',
      email: 'cloudnine@ridesetu.demo',
      phone: '+91 98999 00011',
      address: 'Picture Palace Bus Stand Arcade',
      city: 'Mussoorie',
      destinationId: mussoorieDest._id,
      businessType: 'PARTNERSHIP',
      rentalLicenseNumber: 'UK-MUS-RENT-2023-091',
      verificationStatus: 'VERIFIED',
      rating: 4.9,
      totalReviews: 89,
      commissionRate: 15,
      deliveryRadiusKm: 15,
      baseDeliveryFee: 140,
      isTopRated: true,
      documents: { tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/cloudnine_lic.pdf' },
    },
    {
      userId: vendorUser2._id,
      businessName: 'Doon Express Car & Bike Hub',
      ownerName: 'Vikas Tyagi',
      email: 'doon.express@ridesetu.demo',
      phone: '+91 98123 45678',
      address: 'ISBT Complex, Transport Nagar',
      city: 'Dehradun',
      destinationId: dehradunDest._id,
      businessType: 'PVT_LTD',
      rentalLicenseNumber: 'UK-DDN-RENT-2022-088',
      verificationStatus: 'VERIFIED',
      rating: 4.8,
      totalReviews: 174,
      commissionRate: 15,
      deliveryRadiusKm: 30,
      baseDeliveryFee: 180,
      isTopRated: true,
      documents: { tradeLicenseUrl: 'https://cdn.ridesetu.demo/docs/doon_express_lic.pdf' },
    },
  ]);

  const [vHimalayan, vTapovan, vDoonMobility, vNainiRiders, vMussoorieHeights, vHolyGanga, vKathgodam, vGangaCruise, vCloudNine, vDoonExpress] = vendors;

  console.log('[Seed] Creating 30+ demo rental vehicles across all categories...');
  const vehicles = await Vehicle.create([
    // --- SCOOTERS ---
    {
      vendorId: vHimalayan._id,
      destinationId: rishikeshDest._id,
      brand: 'Honda',
      model: 'Activa 6G',
      variant: 'Deluxe Smart Key (Matte Axis Grey)',
      category: 'SCOOTER',
      year: 2024,
      color: 'Matte Grey',
      registrationNumber: 'UK 07 BD 4821',
      odometer: 4200,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 450,
      pricePerHour: 55,
      weekendPrice: 500,
      securityDeposit: 1000,
      kmLimitPerDay: 150,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      oneWayAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: [
        'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
      ],
      specifications: { engineCc: 109, seatingCapacity: 2, fuelTankCapacityL: 5.3, topSpeedKmph: 85, luggageSpace: '18L Underseat Boot + Front Hook' },
      rating: 4.9,
      totalBookings: 86,
      totalReviews: 42,
      badges: ['VERIFIED VENDOR', 'TOP RATED', 'DOORSTEP DELIVERY', 'FREE HELMET'],
    },
    {
      vendorId: vTapovan._id,
      destinationId: rishikeshDest._id,
      brand: 'TVS',
      model: 'Jupiter 125',
      variant: 'Disc SmartXonnect (Metallic Titanium Grey)',
      category: 'SCOOTER',
      year: 2024,
      color: 'Titanium Grey',
      registrationNumber: 'UK 07 BD 9941',
      odometer: 3100,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 420,
      pricePerHour: 50,
      weekendPrice: 480,
      securityDeposit: 800,
      kmLimitPerDay: 150,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      oneWayAvailable: false,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: [
        'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
      ],
      specifications: { engineCc: 124, seatingCapacity: 2, fuelTankCapacityL: 5.1, topSpeedKmph: 90, luggageSpace: '33L Dual Helmet Boot Space' },
      rating: 4.8,
      totalBookings: 64,
      totalReviews: 31,
      badges: ['VERIFIED VENDOR', 'BIGGEST BOOT', 'GREAT VALUE'],
    },
    {
      vendorId: vGangaCruise._id,
      destinationId: rishikeshDest._id,
      brand: 'Suzuki',
      model: 'Access 125',
      variant: 'Ride Connect Edition (Pearl Mirage White)',
      category: 'SCOOTER',
      year: 2023,
      color: 'Pearl White',
      registrationNumber: 'UK 07 BC 1209',
      odometer: 6500,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 440,
      pricePerHour: 50,
      weekendPrice: 500,
      securityDeposit: 1000,
      kmLimitPerDay: 150,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 124, seatingCapacity: 2, fuelTankCapacityL: 5.0, topSpeedKmph: 92 },
      rating: 4.7,
      totalBookings: 52,
      totalReviews: 24,
      badges: ['VERIFIED VENDOR', 'SMOOTH RIDE'],
    },
    {
      vendorId: vMussoorieHeights._id,
      destinationId: mussoorieDest._id,
      brand: 'TVS',
      model: 'Ntorq 125',
      variant: 'Race XP Tri-Tone Edition',
      category: 'SCOOTER',
      year: 2024,
      color: 'Race Red / Black',
      registrationNumber: 'UK 09 TA 5512',
      odometer: 2800,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 550,
      pricePerHour: 65,
      weekendPrice: 600,
      securityDeposit: 1200,
      kmLimitPerDay: 150,
      excessKmCharge: 5,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 124, seatingCapacity: 2, fuelTankCapacityL: 5.8, topSpeedKmph: 98 },
      rating: 4.9,
      totalBookings: 79,
      totalReviews: 38,
      badges: ['HILL POWER', 'TOP RATED', 'BLUETOOTH NAVIGATION'],
    },
    {
      vendorId: vCloudNine._id,
      destinationId: mussoorieDest._id,
      brand: 'Honda',
      model: 'Activa 125',
      variant: 'H-Smart Premium Edition',
      category: 'SCOOTER',
      year: 2023,
      color: 'Midnight Blue',
      registrationNumber: 'UK 09 TA 8844',
      odometer: 5400,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 500,
      pricePerHour: 60,
      securityDeposit: 1000,
      kmLimitPerDay: 150,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 124, seatingCapacity: 2, fuelTankCapacityL: 5.3, topSpeedKmph: 90 },
      rating: 4.8,
      totalBookings: 61,
      totalReviews: 29,
      badges: ['VERIFIED VENDOR', 'COMFORT SEAT'],
    },
    {
      vendorId: vDoonMobility._id,
      destinationId: dehradunDest._id,
      brand: 'Yamaha',
      model: 'RayZR 125',
      variant: 'Hybrid Fi Street Rally Edition',
      category: 'SCOOTER',
      year: 2024,
      color: 'Matte Copper',
      registrationNumber: 'UK 07 BD 7711',
      odometer: 1900,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 430,
      pricePerHour: 50,
      securityDeposit: 1000,
      kmLimitPerDay: 150,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 125, seatingCapacity: 2, fuelTankCapacityL: 5.2, topSpeedKmph: 90 },
      rating: 4.8,
      totalBookings: 43,
      totalReviews: 21,
      badges: ['ULTRA LIGHTWEIGHT', 'HYBRID MILEAGE'],
    },
    {
      vendorId: vNainiRiders._id,
      destinationId: nainitalDest._id,
      brand: 'Honda',
      model: 'Activa 6G',
      variant: 'Standard BS6',
      category: 'SCOOTER',
      year: 2023,
      color: 'Pearl Siren Blue',
      registrationNumber: 'UK 04 AD 4120',
      odometer: 7200,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 460,
      pricePerHour: 55,
      securityDeposit: 1000,
      kmLimitPerDay: 150,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 109, seatingCapacity: 2, fuelTankCapacityL: 5.3, topSpeedKmph: 85 },
      rating: 4.7,
      totalBookings: 56,
      totalReviews: 27,
      badges: ['VERIFIED VENDOR', 'LAKE RIDE READY'],
    },
    {
      vendorId: vHolyGanga._id,
      destinationId: haridwarDest._id,
      brand: 'TVS',
      model: 'Jupiter 110',
      variant: 'Classic Edition',
      category: 'SCOOTER',
      year: 2023,
      color: 'Autumn Brown',
      registrationNumber: 'UK 08 AH 9920',
      odometer: 8100,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 380,
      pricePerHour: 45,
      securityDeposit: 800,
      kmLimitPerDay: 150,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 109, seatingCapacity: 2, fuelTankCapacityL: 5.0, topSpeedKmph: 82 },
      rating: 4.6,
      totalBookings: 48,
      totalReviews: 19,
      badges: ['BUDGET SAVER', 'VERIFIED VENDOR'],
    },
    {
      vendorId: vKathgodam._id,
      destinationId: haldwaniDest._id,
      brand: 'Honda',
      model: 'Activa 6G',
      variant: 'Deluxe Black Edition',
      category: 'SCOOTER',
      year: 2024,
      color: 'Black',
      registrationNumber: 'UK 04 AD 8821',
      odometer: 3400,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 400,
      pricePerHour: 50,
      securityDeposit: 1000,
      kmLimitPerDay: 150,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 109, seatingCapacity: 2, fuelTankCapacityL: 5.3, topSpeedKmph: 85 },
      rating: 4.9,
      totalBookings: 72,
      totalReviews: 36,
      badges: ['KATHGODAM STATION PICKUP', 'VERIFIED VENDOR'],
    },

    // --- MOTORCYCLES ---
    {
      vendorId: vHimalayan._id,
      destinationId: rishikeshDest._id,
      brand: 'Royal Enfield',
      model: 'Classic 350',
      variant: 'Dark Stealth Black (Dual-Channel ABS)',
      category: 'MOTORCYCLE',
      year: 2024,
      color: 'Stealth Black',
      registrationNumber: 'UK 07 BD 3501',
      odometer: 5100,
      fuelType: 'PETROL',
      transmission: 'MANUAL',
      pricePerDay: 850,
      pricePerHour: 95,
      weekendPrice: 950,
      securityDeposit: 2000,
      kmLimitPerDay: 200,
      excessKmCharge: 6,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      oneWayAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: [
        'https://images.unsplash.com/photo-1558981408-db0ecd8a1ee4?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1558981420-87aa92103a4a?auto=format&fit=crop&w=800&q=80',
      ],
      specifications: { engineCc: 349, seatingCapacity: 2, fuelTankCapacityL: 13.0, topSpeedKmph: 115, luggageSpace: 'Rear Carrier + Saddle Stay Included' },
      rating: 4.9,
      totalBookings: 118,
      totalReviews: 57,
      badges: ['MOST POPULAR', 'HIMALAYAN CRUISER', 'FREE HELMET + CARRIER'],
    },
    {
      vendorId: vHimalayan._id,
      destinationId: rishikeshDest._id,
      brand: 'Royal Enfield',
      model: 'Himalayan 450',
      variant: 'Hanle Black Tubeless Spoke Edition',
      category: 'MOTORCYCLE',
      year: 2024,
      color: 'Hanle Black',
      registrationNumber: 'UK 07 BD 4500',
      odometer: 2400,
      fuelType: 'PETROL',
      transmission: 'MANUAL',
      pricePerDay: 1350,
      pricePerHour: 140,
      weekendPrice: 1500,
      securityDeposit: 3000,
      kmLimitPerDay: 250,
      excessKmCharge: 7,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      oneWayAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: [
        'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1558981408-db0ecd8a1ee4?auto=format&fit=crop&w=800&q=80',
      ],
      specifications: { engineCc: 452, seatingCapacity: 2, fuelTankCapacityL: 17.0, topSpeedKmph: 135, luggageSpace: 'Full Adventure Pannier Rails + USB-C' },
      rating: 5.0,
      totalBookings: 65,
      totalReviews: 34,
      badges: ['NEW 450CC SHERPA', 'OFF-ROAD READY', 'TOP RATED'],
    },
    {
      vendorId: vTapovan._id,
      destinationId: rishikeshDest._id,
      brand: 'Royal Enfield',
      model: 'Hunter 350',
      variant: 'Metro Dapper Ash',
      category: 'MOTORCYCLE',
      year: 2024,
      color: 'Dapper Ash',
      registrationNumber: 'UK 07 BD 3599',
      odometer: 3800,
      fuelType: 'PETROL',
      transmission: 'MANUAL',
      pricePerDay: 750,
      pricePerHour: 85,
      weekendPrice: 850,
      securityDeposit: 1500,
      kmLimitPerDay: 200,
      excessKmCharge: 5,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981420-87aa92103a4a?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 349, seatingCapacity: 2, fuelTankCapacityL: 13.0, topSpeedKmph: 114 },
      rating: 4.8,
      totalBookings: 88,
      totalReviews: 41,
      badges: ['AGILE RETRO', 'EASY CITY RIDE'],
    },
    {
      vendorId: vTapovan._id,
      destinationId: rishikeshDest._id,
      brand: 'Honda',
      model: 'CB350 Hness',
      variant: 'DLX Pro Dual Tone (Matte Steel Black)',
      category: 'MOTORCYCLE',
      year: 2023,
      color: 'Matte Black / Silver',
      registrationNumber: 'UK 07 BC 8831',
      odometer: 6100,
      fuelType: 'PETROL',
      transmission: 'MANUAL',
      pricePerDay: 800,
      pricePerHour: 90,
      securityDeposit: 1500,
      kmLimitPerDay: 200,
      excessKmCharge: 5,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981408-db0ecd8a1ee4?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 348, seatingCapacity: 2, fuelTankCapacityL: 15.0, topSpeedKmph: 120 },
      rating: 4.9,
      totalBookings: 71,
      totalReviews: 35,
      badges: ['REFINED ENGINE', 'TRACTION CONTROL'],
    },
    {
      vendorId: vMussoorieHeights._id,
      destinationId: mussoorieDest._id,
      brand: 'Royal Enfield',
      model: 'Classic 350',
      variant: 'Halcyon Green Chrome',
      category: 'MOTORCYCLE',
      year: 2023,
      color: 'Halcyon Green',
      registrationNumber: 'UK 09 TA 3511',
      odometer: 7800,
      fuelType: 'PETROL',
      transmission: 'MANUAL',
      pricePerDay: 900,
      pricePerHour: 100,
      securityDeposit: 2000,
      kmLimitPerDay: 200,
      excessKmCharge: 6,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981408-db0ecd8a1ee4?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 349, seatingCapacity: 2, fuelTankCapacityL: 13.0, topSpeedKmph: 115 },
      rating: 4.8,
      totalBookings: 94,
      totalReviews: 46,
      badges: ['VINTAGE CHARM', 'HILL TESTED'],
    },
    {
      vendorId: vDoonMobility._id,
      destinationId: dehradunDest._id,
      brand: 'KTM',
      model: 'Duke 250',
      variant: 'Gen 3 Electronic Orange',
      category: 'MOTORCYCLE',
      year: 2024,
      color: 'Orange / White',
      registrationNumber: 'UK 07 BD 2500',
      odometer: 3200,
      fuelType: 'PETROL',
      transmission: 'MANUAL',
      pricePerDay: 950,
      pricePerHour: 110,
      securityDeposit: 2500,
      kmLimitPerDay: 200,
      excessKmCharge: 6,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 249, seatingCapacity: 2, fuelTankCapacityL: 15.0, topSpeedKmph: 140 },
      rating: 4.9,
      totalBookings: 53,
      totalReviews: 26,
      badges: ['THRILL RIDE', 'QUICKSHIFTER'],
    },
    {
      vendorId: vKathgodam._id,
      destinationId: haldwaniDest._id,
      brand: 'Royal Enfield',
      model: 'Himalayan 411',
      variant: 'Gravel Grey BS6',
      category: 'MOTORCYCLE',
      year: 2023,
      color: 'Gravel Grey',
      registrationNumber: 'UK 04 AD 4110',
      odometer: 9200,
      fuelType: 'PETROL',
      transmission: 'MANUAL',
      pricePerDay: 1100,
      pricePerHour: 120,
      securityDeposit: 2500,
      kmLimitPerDay: 250,
      excessKmCharge: 6,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981408-db0ecd8a1ee4?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 411, seatingCapacity: 2, fuelTankCapacityL: 15.0, topSpeedKmph: 125 },
      rating: 4.8,
      totalBookings: 81,
      totalReviews: 39,
      badges: ['KUMAON EXPEDITION', 'SADDLE BAGS READY'],
    },
    {
      vendorId: vNainiRiders._id,
      destinationId: nainitalDest._id,
      brand: 'Yamaha',
      model: 'FZ-S V4',
      variant: 'Deluxe Metallic Grey',
      category: 'MOTORCYCLE',
      year: 2024,
      color: 'Metallic Grey',
      registrationNumber: 'UK 04 AD 1501',
      odometer: 4100,
      fuelType: 'PETROL',
      transmission: 'MANUAL',
      pricePerDay: 650,
      pricePerHour: 75,
      securityDeposit: 1500,
      kmLimitPerDay: 180,
      excessKmCharge: 5,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80'],
      specifications: { engineCc: 149, seatingCapacity: 2, fuelTankCapacityL: 13.0, topSpeedKmph: 110 },
      rating: 4.7,
      totalBookings: 47,
      totalReviews: 22,
      badges: ['LIGHTWEIGHT COMMUTER', 'TRACTION CONTROL'],
    },

    // --- CARS & SUVS ---
    {
      vendorId: vDoonExpress._id,
      destinationId: dehradunDest._id,
      brand: 'Mahindra',
      model: 'Thar 4x4',
      variant: 'LX Hard Top Diesel MT (Napoli Black)',
      category: 'CAR',
      year: 2024,
      color: 'Napoli Black',
      registrationNumber: 'UK 07 BD 4004',
      odometer: 8400,
      fuelType: 'DIESEL',
      transmission: 'MANUAL',
      pricePerDay: 3500,
      pricePerHour: 350,
      weekendPrice: 4000,
      securityDeposit: 5000,
      kmLimitPerDay: 250,
      excessKmCharge: 12,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      oneWayAvailable: true,
      helmetIncluded: false,
      roadsideAssistance: true,
      images: [
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      ],
      specifications: { seatingCapacity: 4, fuelTankCapacityL: 57, topSpeedKmph: 155, luggageSpace: '4 Luggage Bags' },
      rating: 4.9,
      totalBookings: 78,
      totalReviews: 39,
      badges: ['4X4 MOUNTAIN BEAST', 'SELF DRIVE', 'AIRPORT DELIVERY'],
    },
    {
      vendorId: vDoonMobility._id,
      destinationId: dehradunDest._id,
      brand: 'Maruti Suzuki',
      model: 'Swift',
      variant: 'ZXi+ AMT Dual Tone',
      category: 'CAR',
      year: 2024,
      color: 'Luster Blue',
      registrationNumber: 'UK 07 BD 1122',
      odometer: 6200,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 1800,
      pricePerHour: 180,
      weekendPrice: 2100,
      securityDeposit: 3000,
      kmLimitPerDay: 250,
      excessKmCharge: 9,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: false,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80'],
      specifications: { seatingCapacity: 5, fuelTankCapacityL: 37, topSpeedKmph: 160, luggageSpace: '268L Boot Space' },
      rating: 4.8,
      totalBookings: 92,
      totalReviews: 44,
      badges: ['AUTOMATIC', 'HIGH FUEL EFFICIENCY', 'COMPACT MOUNTAIN CAR'],
    },
    {
      vendorId: vKathgodam._id,
      destinationId: haldwaniDest._id,
      brand: 'Hyundai',
      model: 'Creta',
      variant: 'SX (O) Turbo Petrol DCT',
      category: 'CAR',
      year: 2024,
      color: 'Abyss Black',
      registrationNumber: 'UK 04 AD 7700',
      odometer: 5100,
      fuelType: 'PETROL',
      transmission: 'AUTOMATIC',
      pricePerDay: 2800,
      pricePerHour: 280,
      weekendPrice: 3200,
      securityDeposit: 4000,
      kmLimitPerDay: 250,
      excessKmCharge: 11,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: false,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80'],
      specifications: { seatingCapacity: 5, fuelTankCapacityL: 50, topSpeedKmph: 180, luggageSpace: '433L Boot Space' },
      rating: 4.9,
      totalBookings: 61,
      totalReviews: 30,
      badges: ['PREMIUM SUV', 'PANORAMIC SUNROOF', 'CRUISE CONTROL'],
    },

    // --- ELECTRIC VEHICLES (EV) ---
    {
      vendorId: vHimalayan._id,
      destinationId: rishikeshDest._id,
      brand: 'Ather',
      model: '450X Gen 3',
      variant: 'Pro Pack (Space Grey with Fast Charging)',
      category: 'EV',
      year: 2024,
      color: 'Space Grey',
      registrationNumber: 'UK 07 BD 450E',
      odometer: 1800,
      fuelType: 'ELECTRIC',
      transmission: 'AUTOMATIC',
      pricePerDay: 500,
      pricePerHour: 60,
      weekendPrice: 550,
      securityDeposit: 1000,
      kmLimitPerDay: 120,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: [
        'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
      ],
      specifications: { batteryCapacityKwh: 3.7, rangeKm: 110, topSpeedKmph: 90, seatingCapacity: 2, luggageSpace: '22L Boot + Portable Charger Included' },
      rating: 5.0,
      totalBookings: 58,
      totalReviews: 29,
      badges: ['100% ECO GREEN', 'FREE CHARGING IN TAPOVAN', 'TOUCHSCREEN MAPS'],
    },
    {
      vendorId: vDoonMobility._id,
      destinationId: dehradunDest._id,
      brand: 'Ola',
      model: 'S1 Pro Gen 2',
      variant: 'Jet Black Edition',
      category: 'EV',
      year: 2024,
      color: 'Jet Black',
      registrationNumber: 'UK 07 BD 990E',
      odometer: 2200,
      fuelType: 'ELECTRIC',
      transmission: 'AUTOMATIC',
      pricePerDay: 480,
      pricePerHour: 55,
      weekendPrice: 530,
      securityDeposit: 1000,
      kmLimitPerDay: 130,
      excessKmCharge: 4,
      isAvailable: true,
      isVerified: true,
      deliveryAvailable: true,
      helmetIncluded: true,
      roadsideAssistance: true,
      images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80'],
      specifications: { batteryCapacityKwh: 4.0, rangeKm: 140, topSpeedKmph: 120, seatingCapacity: 2, luggageSpace: '34L Boot Space' },
      rating: 4.8,
      totalBookings: 49,
      totalReviews: 23,
      badges: ['HYPER MODE', 'LONG RANGE EV'],
    },
  ]);

  const [activaRishikesh, jupiterRishikesh, accessRishikesh, ntorqMussoorie, classicRishikesh, himalayanRishikesh, tharDehradun] = vehicles;

  console.log('[Seed] Creating demo coupons...');
  await Coupon.create([
    {
      code: 'FIRST50',
      description: 'Get 50% OFF (up to ₹200) on your very first rental ride',
      discountType: 'PERCENTAGE',
      discountValue: 50,
      minimumBookingValue: 400,
      maximumDiscount: 200,
      applicableCities: [],
      expiryDate: new Date('2027-12-31'),
      usageLimit: 10000,
      perUserLimit: 1,
      isActive: true,
    },
    {
      code: 'RISHIKESH100',
      description: 'Flat ₹100 OFF on any two-wheeler rental in Rishikesh',
      discountType: 'FLAT',
      discountValue: 100,
      minimumBookingValue: 500,
      maximumDiscount: 100,
      applicableCities: ['Rishikesh'],
      applicableVehicleCategories: ['SCOOTER', 'MOTORCYCLE', 'EV'],
      expiryDate: new Date('2027-12-31'),
      usageLimit: 5000,
      perUserLimit: 2,
      isActive: true,
    },
    {
      code: 'WELCOME10',
      description: '10% discount on all bookings above ₹1,000',
      discountType: 'PERCENTAGE',
      discountValue: 10,
      minimumBookingValue: 1000,
      maximumDiscount: 500,
      applicableCities: [],
      expiryDate: new Date('2027-12-31'),
      usageLimit: 5000,
      perUserLimit: 3,
      isActive: true,
    },
    {
      code: 'HIMALAYA15',
      description: '15% OFF on Royal Enfield and Adventure bikes',
      discountType: 'PERCENTAGE',
      discountValue: 15,
      minimumBookingValue: 1500,
      maximumDiscount: 600,
      applicableCities: [],
      applicableVehicleCategories: ['MOTORCYCLE'],
      expiryDate: new Date('2027-12-31'),
      usageLimit: 2000,
      perUserLimit: 2,
      isActive: true,
    },
  ]);

  console.log('[Seed] Creating demo bookings & digital handover reports...');
  const samplePickup = new Date();
  samplePickup.setDate(samplePickup.getDate() - 2);
  const sampleReturn = new Date();
  sampleReturn.setDate(sampleReturn.getDate() - 1);

  const completedBooking = await Booking.create({
    bookingNumber: 'RS-2026-104928',
    customerId: customerUser._id,
    vendorId: vHimalayan._id,
    vehicleId: activaRishikesh._id,
    destinationId: rishikeshDest._id,
    pickupDateTime: samplePickup,
    returnDateTime: sampleReturn,
    pickupType: 'HOTEL_DELIVERY',
    pickupLocation: 'Zostel Tapovan, Rishikesh',
    dropoffLocation: 'Zostel Tapovan, Rishikesh',
    rentalDurationDays: 1,
    rentalDurationHours: 24,
    basePrice: 450,
    deliveryCharge: 120,
    platformFee: 49,
    taxes: 111,
    securityDeposit: 1000,
    discountAmount: 100,
    totalPayable: 1630,
    depositStatus: 'REFUNDED',
    bookingStatus: 'COMPLETED',
    paymentStatus: 'PAID',
    kycVerified: true,
    customerDetails: {
      fullName: 'Aarav Sharma',
      phone: '+91 98765 43210',
      email: 'customer@ridesetu.demo',
      drivingLicenseNumber: 'UK0720210084920',
    },
    emergencyContact: {
      name: 'Rohan Sharma',
      phone: '+91 98765 43219',
      relation: 'Brother',
    },
    couponCode: 'RISHIKESH100',
  });

  // Digital Handover (Pickup)
  const pickupReport = await DigitalHandoverReport.create({
    bookingId: completedBooking._id,
    vehicleId: activaRishikesh._id,
    handoverType: 'PICKUP',
    odometerReading: 4120,
    fuelBatteryLevel: 100,
    existingScratches: [
      { id: 'sc-1', zone: 'Exhaust Heat Shield', description: 'Minor 2cm hairline paint scratch', severity: 'MINOR' },
    ],
    photos: {
      frontUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&q=80',
      backUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
      leftUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&q=80',
      rightUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
      meterUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=400&q=80',
    },
    helmetCount: 1,
    accessoriesGiven: ['1 ISI Helmet', 'Vehicle Registration Copy', 'First Aid Kit'],
    customerSignatureConfirmed: true,
    customerSignatureName: 'Aarav Sharma',
    vendorAgentName: 'Vikram Negi (Partner Agent)',
    remarks: 'Delivered in mint showroom condition to Zostel Tapovan reception.',
    timestamp: samplePickup,
  });

  // Digital Handover (Return)
  const returnReport = await DigitalHandoverReport.create({
    bookingId: completedBooking._id,
    vehicleId: activaRishikesh._id,
    handoverType: 'RETURN',
    odometerReading: 4185,
    fuelBatteryLevel: 95,
    existingScratches: [
      { id: 'sc-1', zone: 'Exhaust Heat Shield', description: 'Minor 2cm hairline paint scratch', severity: 'MINOR' },
    ],
    photos: {
      frontUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&q=80',
      backUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
      leftUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&q=80',
      rightUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
      meterUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=400&q=80',
    },
    helmetCount: 1,
    accessoriesGiven: ['1 ISI Helmet', 'Vehicle Registration Copy', 'First Aid Kit'],
    customerSignatureConfirmed: true,
    customerSignatureName: 'Aarav Sharma',
    vendorAgentName: 'Vikram Negi (Partner Agent)',
    remarks: 'Vehicle returned in spotless condition. Total distance ridden: 65 km. Zero new damage. 100% deposit refunded immediately.',
    timestamp: sampleReturn,
  });

  completedBooking.handoverPickupId = pickupReport._id;
  completedBooking.handoverReturnId = returnReport._id;
  await completedBooking.save();

  // Create Review
  await Review.create({
    bookingId: completedBooking._id,
    customerId: customerUser._id,
    customerName: 'Aarav Sharma',
    customerAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    vehicleId: activaRishikesh._id,
    vendorId: vHimalayan._id,
    overallRating: 5,
    vehicleConditionRating: 5,
    vendorBehaviorRating: 5,
    pickupExperienceRating: 5,
    pricingTransparencyRating: 5,
    reviewText: 'Outstanding experience! Vikram delivered the Activa 6G right to our hostel in Tapovan on time. The digital handover photos gave complete peace of mind, and the scooter climbed up to Neelkanth smoothly. Highly recommend RideSetu over unverified roadside shops!',
    vendorReply: {
      text: 'Thank you so much Aarav! It was a pleasure hosting you in Rishikesh. Hope to see you again on your next mountain trip!',
      repliedAt: new Date(),
    },
    isVerifiedRental: true,
  });

  // Create an upcoming active booking
  const activePickup = new Date();
  activePickup.setDate(activePickup.getDate() + 1);
  const activeReturn = new Date();
  activeReturn.setDate(activeReturn.getDate() + 3);

  await Booking.create({
    bookingNumber: 'RS-2026-928411',
    customerId: customerUser._id,
    vendorId: vHimalayan._id,
    vehicleId: classicRishikesh._id,
    destinationId: rishikeshDest._id,
    pickupDateTime: activePickup,
    returnDateTime: activeReturn,
    pickupType: 'VENDOR_PICKUP',
    pickupLocation: 'Main Tapovan Bypass Road, near Swiss Cottage',
    dropoffLocation: 'Main Tapovan Bypass Road, near Swiss Cottage',
    rentalDurationDays: 2,
    rentalDurationHours: 48,
    basePrice: 1700,
    deliveryCharge: 0,
    platformFee: 49,
    taxes: 315,
    securityDeposit: 2000,
    discountAmount: 150,
    totalPayable: 3914,
    depositStatus: 'PENDING',
    bookingStatus: 'CONFIRMED',
    paymentStatus: 'PAID',
    kycVerified: true,
    customerDetails: {
      fullName: 'Aarav Sharma',
      phone: '+91 98765 43210',
      email: 'customer@ridesetu.demo',
      drivingLicenseNumber: 'UK0720210084920',
    },
    emergencyContact: {
      name: 'Rohan Sharma',
      phone: '+91 98765 43219',
      relation: 'Brother',
    },
    couponCode: 'WELCOME10',
  });

  // Block maintenance for one vehicle to test calendar and availability logic
  const maintStart = new Date();
  maintStart.setDate(maintStart.getDate() + 5);
  const maintEnd = new Date();
  maintEnd.setDate(maintEnd.getDate() + 7);

  await VehicleAvailability.create({
    vehicleId: jupiterRishikesh._id,
    startDate: maintStart,
    endDate: maintEnd,
    reason: 'MAINTENANCE',
    notes: 'Scheduled 5,000 km periodic engine oil service and brake inspection.',
  });

  console.log('[Seed] Database seeding completed successfully!');
  await mongoose.disconnect();
}

// Execute if run directly
if (require.main === module) {
  seedDatabase()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('[Seed Error]:', err);
      process.exit(1);
    });
}
